{% set name = "KIN" %}
{% set version = "3.1.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/DivyaratanPopli/Kinship_Inference/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 946e872b10db0ae8249c3278ea2b3df8c57ae840fd6c9e8662cb5692da4b93ab

build:
  number: 0
  noarch: python
  script:
    - "python -m pip install ./pypackage/kin -vv --no-deps"
    - "python -m pip install ./pypackage/kingaroo -vv --no-deps"
    - "mkdir -p ${PREFIX}/bin"
    # - "cp KINgaroo ${PREFIX}/bin/kingaroo"
    # - "cp KIN ${PREFIX}/bin/kin"
    # - "chmod +x ${PREFIX}/bin/kingaroo ${PREFIX}/bin/kin"
  run_exports:
    - {{ pin_subpackage("kin", max_pin="x.x") }}

requirements:
  run:
    - python >=3.8
    - scipy >=1.8.0
    - numpy >=1.21.1
    - pandas >=1.3.1
    - numba >=0.55.1
    - pysam >=0.19.0
    - pybedtools >=0.9.0
    - samtools >=1.15
    - bcftools >=1.15


test:
  commands:
    - KIN --help
    - KINgaroo --help

about:
  home: https://github.com/DivyaratanPopli/Kinship_Inference
  license: GPL-3.0-only
  # license_file: LICENCE ## Exists in main but not tag
  summary: "A tool to estimate pairwise relatedness from ancient DNA, taking in account contamination, ROH, ascertainment bias."
  doc_url: https://github.com/DivyaratanPopli/Kinship_Inference/blob/main/README.md

extra:
  recipe-maintainers:
    - TCLamnidis
