{% set version = "2.0.5" %}

package:
  name: bamtable
  version: {{ version }}

build:
  # skip: true # [osx]
  number: 0
  run_exports:
    - {{ pin_subpackage("bamtable", max_pin="x") }}

source:
  ## This recipe doesn't work because the URL lacks a valid SSL certificate.
  url: http://bioinf.eva.mpg.de/BamTable/BamTable-{{ version }}.tar.gz
  sha256: 6cae975b208e4d208ebc6e08acd19cf43f01597f6dea6931dbfc0fff2e553537

requirements:
  build:
    - make
    - popt
    - {{ compiler('cxx') }} 
  # host:

about:
  home: https://bioinf.eva.mpg.de/BamTable/
  license: MIT
  license_file: LICENSE
  summary: Filters sorted bam files according to criteria and print a table with results.

test:
  commands:
    - BamTable --help
    - BamTable --version

extra:
  additional-platforms:
    - linux-aarch64
