{% set version = "1.0.0.1" %}
{% set name = "poseidon-qjanno" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/poseidon-framework/qjanno/releases/download/v{{ version }}/qjanno-Linux # [linux]
    md5: 058e7cdcc3baa680eada1532e4cccf2e # [linux]
  - url: https://github.com/poseidon-framework/qjanno/releases/download/v{{ version }}/qjanno-macOS # [osx]
    md5: 7614d2fffb3f5bdeb7df418d26b188ed # [osx]

build:
  number: 0
  script:
    - "mkdir -p $PREFIX/bin"
    - "mv qjanno* $PREFIX/bin/qjanno"
    - "chmod u+x $PREFIX/bin/qjanno"
  run_exports:
    - {{ pin_subpackage("{{ name }}", max_pin=None) }}

requirements:
  build:
    # Precompiled binaries still link against libgcc
    - {{ compiler('c') }}
  host:
    - zlib
    - gmp
  run:
    - zlib
    - gmp

test:
  commands:
      - qjanno --version

about:
  home: https://www.poseidon-adna.org/#/
  license: MIT
  summary: "A CLI tool to run SQL queries on Poseidon .janno files."
