{% set version = "1.0.0.1" %}
package:
  name: poseidon-qjanno
  version: {{ version }}

source:
  - url: https://github.com/poseidon-framework/qjanno/releases/download/v{{ version }}/qjanno-conda-linux # [linux]
    md5: 7b929626c6eec7665911bacdf59e4288 # [linux]
  - url: https://github.com/poseidon-framework/qjanno/releases/download/v{{ version }}/qjanno-macOS # [osx]
    md5: 9d1ead73e678fa2f51a70a933b0bf017 # [osx]

build:
  number: 0
  script:
    - "mkdir -p $PREFIX/bin"
    - "mv qjanno* $PREFIX/bin/qjanno"
    - "chmod u+x $PREFIX/bin/qjanno"
  run_exports:
    - {{ pin_subpackage("poseidon-qjanno", max_pin=None) }}

requirements:
  build:
    # Precompiled binaries still link against libgcc
    - {{ compiler('c') }}
  host:
    - zlib
    - gmp
  run:
    - zlib
    - gmp

test:
  commands:
      - qjanno --version

about:
  home: https://www.poseidon-adna.org/#/
  license: MIT
  summary: "A CLI tool to run SQL queries on Poseidon .janno files."
