{% set name = "emu-pca" %}
{% set version = "v1.0" %}

package:
  name: "{{ name|lower }}"
  version: {{ version|replace("v", "") }}

source:
  url: 'https://github.com/Rosemeis/emu/archive/refs/tags/{{ version }}.tar.gz'
  md5sum: b79e9a2f72b8b83361a5542edc1c4ca7

build:
  noarch: generic
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  run_exports:
    {{ pin_subpackage('emu', max_pin="x.x") }}

requirements:
  run:
    - python
    - numpy
    - cython

test:
  commands:
    - emu-pca --help

about:
  home: https://github.com/Rosemeis/emu
  license: GPL-3
  license_file: LICENSE
  summary: EM-PCA for Ultra-low Coverage Sequencing Data.

